PackageIdentifier: nutoo_.Flux
PackageVersion: 0.1.0
PackageLocale: ko
Publisher: nutoo_
PackageName: Flux
License: MIT
ShortDescription: A datapack compiler
Installers:
  - Architecture: x64
    InstallerType: portable
    InstallerUrl: https://github.com/gonggo124/objective-mcfunction/releases/download/v0.1.0/omfn_windows.exe
    InstallerSha256: 90ec51b9a1f935a6536d3528f81468f56c70bb2e75bb3e8a931b0498db8d81f5
ManifestType: "singleton"
ManifestVersion: 1.6.0
